// Package {{ .Package }}.
//
// Code generated by github.com/kukymbr/configen DO NOT EDIT.
// The configen version: {{ .Version }}

// Source: {{ .SourcePath }}
package {{ .Package }}

// TODO: Generated code template goes here.
