// Package readme contains configuration read-only provider.
//
// Code generated by github.com/kukymbr/configen; DO NOT EDIT.
// Generator version: unknown (revision unknown, built at 2025-10-04 00:00:00)
package readme

type Config struct {
	instanceID int
	app        struct {
		env       string
		namespace string
		domain    string
	}
	logger struct {
		level string
	}

	origin any
}

func (c Config) InstanceID() int {
	return c.instanceID
}

// App is an application common settings.
func (c Config) App() struct {
	env       string
	namespace string
	domain    string
} {
	return c.app
}

// Logger is a logging setup values.
func (c Config) Logger() struct {
	level string
} {
	return c.logger
}

// NewConfig is a constructor converting config into the Config.
func NewConfig(dto config) Config {
	return Config{
		instanceID: dto.InstanceID,
		app: struct {
			env       string
			namespace string
			domain    string
		}{
			env:       dto.App.Env,
			namespace: dto.App.Namespace,
			domain:    dto.App.Domain,
		},
		logger: struct {
			level string
		}{
			level: dto.Logger.Level,
		},

		origin: dto,
	}
}

type ConfigAppProvider struct {
	env       string
	namespace string
	domain    string

	origin any
}

func (c ConfigAppProvider) Env() string {
	return c.env
}

func (c ConfigAppProvider) Namespace() string {
	return c.namespace
}

func (c ConfigAppProvider) Domain() string {
	return c.domain
}

type ConfigLoggerProvider struct {
	level string

	origin any
}

func (c ConfigLoggerProvider) Level() string {
	return c.level
}
