// Package {{ .PackageName }} contains configuration read-only provider.
//
// Code generated by github.com/kukymbr/configen; DO NOT EDIT.
// Generator version: {{ .Version }}
package {{ .PackageName }}

import(
{{ range .Imports }}
    "{{ . }}"
{{ end }}
)

{{ range $name, $st := .Structs }}
type {{ $st.Name }} struct {
{{- range $st.Fields }}
    {{- if and .IsStruct .StructInfo.IsAnonymous }}
        {{ .Name }} struct {
            {{- range .StructInfo.Fields }}
                {{ .Name }} {{ .TypeName }}
            {{- end }}
        }
    {{- else }}
	    {{ .Name }} {{ .TypeName }}
	{{- end }}
{{- end }}
}

{{ range $st.Fields }}
{{ if .Comment }}// {{ .Comment }}{{ end }}func (c {{ $st.Name }}) {{ .ExportName }}() {{ .TypeName }} {
	return c.{{ .Name }}
}
{{ end }}

{{ if not $st.IsAnonymous }}
// Constructor for {{ $st.Name }}.
func New{{ $st.Name }}(dto {{ $st.SourceStructName }}) {{ $st.Name }} {
	return {{ $st.Name }}{
		{{- range $fieldIndex, $field := $st.Fields }}
            {{- if $field.IsStruct -}}
                {{- if not $field.StructInfo.IsAnonymous }}
                    {{ $field.Name }}: New{{ $field.TypeName }}(dto.{{ $field.ExportName }}),
                {{- else }}
                    {{ $field.Name }}: struct {
                        {{- range .StructInfo.Fields }}
                            {{ .Name }} {{ .TypeName }}
                        {{- end }}
                    }{
                        {{- range .StructInfo.Fields }}
                            {{ .Name }}: dto.{{ $field.ExportName }}.{{ .ExportName }},
                        {{- end }}
                    },
                {{- end }}
            {{- else }}
                {{ $field.Name }}: dto.{{ $field.ExportName }},
            {{- end }}
		{{- end }}
	}
}
{{ end }}
{{ end }}
