// Package {{ .PackageName }} contains configuration read-only provider.
//
// Code generated by github.com/kukymbr/configen; DO NOT EDIT.
// Generator version: {{ .Version }}
package {{ .PackageName }}

import(
{{ range .Imports }}
    "{{ . }}"
{{ end }}
)

{{ range $name, $st := .Structs }}
type {{ $st.Name }} struct {
{{- range $st.Fields }}
	{{ .Name }} {{ .TypeName }}
{{- end }}
}

{{ range $st.Fields }}
{{ if .Comment }}// {{ .Comment }}{{ end }}func (c {{ $st.Name }}) {{ .ExportName }}() {{ .TypeName }} {
	return c.{{ .Name }}
}
{{ end }}

// Constructor for {{ $st.Name }}.
func New{{ $st.Name }}(dto {{ $st.SourceStructName }}) {{ $st.Name }} {
	return {{ $st.Name }}{
		{{- range $st.Fields }}
		{{ .Name }}: {{ if .IsStruct }}New{{ .TypeName }}(dto.{{ .ExportName }}){{ else }}dto.{{ .ExportName }}{{ end }},
		{{- end }}
	}
}
{{ end }}
